name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - anaconda=2022.05
  - anaconda-client=1.9.0
  - anaconda-navigator=2.1.4
  - anaconda-project=0.10.2
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.2
  - astroid=2.6.6
  - astropy=5.0.4
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - automat=20.2.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - bitarray=2.4.1
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boto3=1.21.32
  - botocore=1.24.32
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - cffi=1.15.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - click=8.0.4
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  - colorcet=2.0.6
  - conda=4.12.0
  - conda-build=3.21.8
  - conda-content-trust=0.1.1
  - conda-env=2.6.0
  - conda-pack=0.6.0
  - conda-package-handling=1.8.1
  - conda-repo-cli=1.0.4
  - conda-token=0.3.0
  - conda-verify=3.4.2
  - constantly=15.1.0
  - cookiecutter=1.7.3
  - cssselect=1.1.0
  - cudatoolkit=11.3.1
  - curl=7.82.0
  - cycler=0.11.0
  - cython=0.29.28
  - cytoolz=0.11.0
  - daal4py=2021.5.0
  - dal=2021.5.1
  - dask=2022.2.1
  - dask-core=2022.2.1
  - dataclasses=0.8
  - datashader=0.13.0
  - datashape=0.5.4
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2022.2.1
  - docutils=0.17.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.4
  - ffmpeg=4.3
  - filelock=3.6.0
  - flake8=3.9.2
  - flask=1.1.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fsspec=2022.2.0
  - future=0.18.2
  - gensim=4.1.2
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-api-core=1.25.1
  - google-cloud-core=1.7.1
  - google-cloud-storage=1.31.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.1
  - googleapis-common-protos=1.53.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.14.8
  - hvplot=0.7.3
  - hyperlink=21.0.0
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.3.0
  - importlib_metadata=4.11.3
  - incremental=21.3.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.5
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=23.4.0
  - krb5=1.19.2
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcrc32c=1.1.1
  - libcurl=7.82.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblief=0.11.5
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.42.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.38.0
  - locket=0.2.1
  - lxml=4.8.0
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - multidict=5.2.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - navigator-updater=0.2.1
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - networkx=2.7.1
  - nltk=3.7
  - nose=1.3.7
  - notebook=6.4.8
  - numba=0.55.1
  - numexpr=2.8.1
  - numpydoc=1.2
  - olefile=0.46
  - oniguruma=6.9.7.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - panel=0.13.0
  - param=1.12.0
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - patchelf=0.13
  - pathspec=0.7.0
  - patsy=0.5.2
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - pkginfo=1.8.2
  - plotly=5.6.0
  - pluggy=1.0.0
  - poyo=0.5.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protego=0.1.16
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-lief=0.11.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pyct=0.4.6
  - pycurl=7.44.1
  - pydispatcher=2.0.5
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pygments=2.11.2
  - pyhamcrest=2.0.2
  - pyjwt=2.1.0
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyodbc=4.0.32
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=7.1.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python-snappy=0.6.0
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pyviz_comms=2.0.2
  - pywavelets=1.3.0
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.3.0
  - queuelib=1.5.0
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - requests-file=1.5.1
  - ripgrep=12.1.1
  - rope=0.22.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - s3transfer=0.5.0
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2021.5.0
  - scrapy=2.6.1
  - seaborn=0.11.2
  - secretstorage=3.3.1
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - smart_open=5.1.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlite=3.38.2
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - sympy=1.10.1
  - tabulate=0.8.9
  - tbb=2021.5.0
  - tbb4py=2021.5.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.11
  - tldextract=3.2.0
  - toml=0.10.2
  - tomli=1.2.2
  - toolz=0.11.2
  - torchaudio=0.10.0
  - torchvision=0.11.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - tzdata=2022a
  - ujson=5.1.0
  - unidecode=1.2.0
  - unixodbc=2.3.9
  - urllib3=1.26.9
  - w3lib=1.21.0
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wget=1.21.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wurlitzer=3.0.2
  - xarray=0.20.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.6.3
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zlib=1.2.12
  - zope=1.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - absl-py==1.1.0
    - aioredis==1.3.1
    # - aivdeploy==0.0.3
    # - aivdetection==1.0.4
    # - aivobbdetection==0.0.7
    - albumentations==1.3.0
    - asgiref==3.5.2
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - autobahn==22.5.1
    - bidict==0.22.1
    - cachetools==5.2.0
    - certifi==2022.6.15
    - channels==3.0.4
    - channels-redis==3.4.0
    - charset-normalizer==2.0.12
    - coloredlogs==15.0.1
    - commonmark==0.9.1
    - cryptography==37.0.2
    - daphne==3.0.2
    - deprecated==1.2.13
    - dill==0.3.6
    - django==4.0.4
    - django-redis==5.2.0
    - djangorestframework==3.13.1
    - efficientnet==1.1.1
    - etils==0.9.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gputil==1.4.0
    - gputils==1.0.6
    # - graphsurgeon==0.4.5
    - greenlet==1.1.2
    - grpcio==1.47.0
    - h5py==3.7.0
    - hiredis==2.0.0
    - huggingface-hub==0.11.1
    - humanfriendly==10.0
    - image-classifiers==1.0.0
    - imgviz==1.5.0
    - importlib==1.0.4
    - importlib-metadata==4.11.4
    - importlib-resources==5.10.1
    - install==1.3.5
    - keras==2.9.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.3
    - libclang==14.0.1
    - littleutils==0.2.2
    - mako==1.2.2
    - markdown==3.3.7
    - matplotlib==3.2.2
    - msgpack==1.0.4
    - natsort==8.1.0
    - numpy==1.22.3
    - nvidia-smi==0.1.3
    - oauthlib==3.2.0
    - onnx==1.12.0
    - onnxruntime==1.13.1
    - onnxsim==0.4.13
    - opencv-python-headless==4.6.0.66
    - opt-einsum==3.3.0
    - platformdirs==2.5.2
    - promise==2.3
    - protobuf==3.19.4
    - psycopg2-binary==2.9.4
    - pycocotools==2.0.5
    - pycuda==2022.1
    - pynvml==11.5.0
    - pyopenssl==22.0.0
    - pyparsing==3.0.9
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - python-engineio==4.4.1
    - python-socketio==5.8.0
    - pytools==2022.1.12
    - pytz==2022.1
    - qtpy==2.1.0
    - qudida==0.0.4
    - redis==4.3.4
    - requests-oauthlib==1.3.1
    - rich==13.0.1
    - rsa==4.8
    - scipy==1.8.1
    - service-identity==21.1.0
    - shapely==2.0.1
    - simplejson==3.17.6
    - sorcery==0.2.2
    - sqlalchemy==1.4.36
    - sqlparse==0.4.2
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    # - tensorflow==2.10.0
    - tensorflow-datasets==4.7.0
    - tensorflow-estimator==2.9.0
    - tensorflow-gpu==2.9.1
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-metadata==1.12.0
    - tensorrt==8.5.1.7
    - termcolor==1.1.0
    - terminaltables==3.1.10
    - tf2onnx==1.12.0
    - timm==0.6.12
    - twisted==22.4.0
    - txaio==22.2.1
    - typing-extensions==4.2.0
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.8.0
# prefix: /root/anaconda3
