# commands:
# docker build -t aiv-image .
# docker run -it --gpus all -v /home/jay/mnt/hdd/workspace:/app/workspace --name aiv_test01 aiv-image /bin/bash 
# conda env update --file environment.yml --name base


# FROM nvidia/cuda:11.7.1-devel-ubuntu20.04
FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

# # Install base utilities
# RUN apt-get update 
# RUN apt-get install -y build-essential
# RUN apt-get install -y wget 
# RUN apt-get clean
# RUN rm -rf /var/lib/apt/lists/*

# # Install miniconda
# ENV CONDA_DIR /opt/conda
# RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -O ~/miniconda.sh && \
#      /bin/bash ~/miniconda.sh -b -p /opt/conda

# # Put conda in path so we can use conda activate
# ENV PATH=$CONDA_DIR/bin:$PATH

# RUN conda --version

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

# COPY environment.yml /tmp/environment.yml

RUN apt-get update && \
    apt-get install -y wget && rm -rf /var/lib/apt/lists/* && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh && \
    bash Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -b &&\
    rm -f Miniconda3-py39_23.1.0-1-Linux-x86_64.sh &&\
    conda --version &&\
    apt-get install libpq-dev
# RUN conda env update --file /tmp/environment.yml --name base

